
import React from 'react';
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
    Star, 
    ArrowRight, 
    Zap,
    Users,
    Check,
    Sparkles
} from "lucide-react";
import { track, AREA } from '@/components/core/telemetry';

import { empfehlungsEngine } from '../foerderung/IntelligenteEmpfehlungsEngine';
import { useProfileUpdateListener } from '@/components/UserProfileContext'; // New import

export default function PersonalizedRecommendations({ 
    recommendations: initialRecommendations, 
    user: initialUser,
    onRecommendationClick 
}) {
    // Internal state to manage recommendations and user profile
    const [recommendations, setRecommendations] = React.useState(initialRecommendations);
    const [user, setUser] = React.useState(initialUser);
    
    // State for intelligent recommendations generated by the engine
    const [intelligentEmpfehlungen, setIntelligentEmpfehlungen] = React.useState([]);
    const [isLoading, setIsLoading] = React.useState(true);

    // ZEPTO STEP 10.14: Auto-update recommendations when profile changes
    // This hook listens for profile updates across the app and triggers a refresh
    useProfileUpdateListener(async ({ eventType, data }) => {
        if (eventType === 'profile_updated' || eventType === 'profile_refreshed') {
            console.log('📊 PersonalizedRecommendations: Profile updated, recalculating...');
            setUser(data.user); // Update the internal user state with the latest profile data
            
            // Track the interaction if observability is enabled
            if (window.MiMiCheckObservability) {
                window.MiMiCheckObservability.trackUserInteraction(
                    'recommendations_auto_refresh',
                    'PersonalizedRecommendations',
                    { eventType, recommendationsCount: recommendations.length } // Use the current recommendations state for tracking
                );
            }
        }
    }, []); // Empty dependency array ensures this effect runs once on mount

    // Effect to update internal state whenever the props `initialRecommendations` or `initialUser` change
    React.useEffect(() => {
        setRecommendations(initialRecommendations);
        setUser(initialUser);
    }, [initialRecommendations, initialUser]);

    // Effect to load intelligent recommendations based on the current user state
    React.useEffect(() => {
        const loadIntelligentEmpfehlungen = async () => {
            setIsLoading(true);
            if (user?.lebenssituation) { // Only attempt AI recommendation if user has a defined 'lebenssituation'
                try {
                    const empfehlungen = await empfehlungsEngine.generiereEmpfehlungen(user, 6);
                    setIntelligentEmpfehlungen(empfehlungen);
                } catch (error) {
                    console.error('Fehler beim Laden der Empfehlungen:', error);
                    // Fallback to the generic recommendations from props if AI recommendation fails
                    setIntelligentEmpfehlungen(recommendations || []); 
                }
            } else {
                // If no user.lebenssituation, directly fall back to the generic recommendations from props
                setIntelligentEmpfehlungen(recommendations || []); 
            }
            setIsLoading(false);
        };

        // This effect runs when the internal `user` state or `recommendations` state changes,
        // ensuring recommendations are always up-to-date.
        loadIntelligentEmpfehlungen();
    }, [user, recommendations]);

    // `aktuelleEmpfehlungen` will always contain the actively displayed recommendations
    // (either AI-generated or the provided generic fallback).
    const aktuelleEmpfehlungen = intelligentEmpfehlungen;

    const handleRecommendationClick = (leistung) => {
        track('recommendation.clicked', AREA.DASHBOARD, {
            leistungId: leistung.id,
            leistungTitel: leistung.titel,
            kategorie: leistung.kategorie,
            anspruchswahrscheinlichkeit: leistung.anspruchswahrscheinlichkeit
        });

        if (onRecommendationClick) {
            onRecommendationClick(leistung);
        }
    };

    if (isLoading) {
        return (
            <Card className="border-none shadow-2xl h-full bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl glass-morphism">
                <CardHeader className="border-b border-white/10 p-8">
                    <CardTitle className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-3 humanistic-serif">
                        <div className="w-8 h-8 bg-gradient-to-br from-amber-400 to-orange-500 rounded-xl flex items-center justify-center">
                            <Star className="w-5 h-5 text-white" />
                        </div>
                        Für Sie empfohlen
                    </CardTitle>
                </CardHeader>
                <CardContent className="p-8">
                    <div className="space-y-6">
                        {Array(6).fill(0).map((_, i) => (
                            <div key={i} className="animate-pulse">
                                <div className="h-5 bg-gradient-to-r from-slate-200 via-slate-300 to-slate-200 dark:from-slate-700 dark:via-slate-600 dark:to-slate-700 rounded-xl mb-3"></div>
                                <div className="h-4 bg-gradient-to-r from-slate-200 via-slate-300 to-slate-200 dark:from-slate-700 dark:via-slate-600 dark:to-slate-700 rounded-lg w-2/3"></div>
                            </div>
                        ))}
                    </div>
                </CardContent>
            </Card>
        );
    }

    if (aktuelleEmpfehlungen.length === 0) {
        return (
            <Card className="border-none shadow-2xl h-full bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl glass-morphism">
                <CardHeader className="border-b border-white/10 p-8">
                    <CardTitle className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-3 humanistic-serif">
                        <div className="w-8 h-8 bg-gradient-to-br from-amber-400 to-orange-500 rounded-xl flex items-center justify-center">
                            <Star className="w-5 h-5 text-white" />
                        </div>
                        Für Sie empfohlen
                    </CardTitle>
                </CardHeader>
                <CardContent className="p-8 text-center flex items-center justify-center min-h-[400px]">
                    <div>
                        <div className="w-20 h-20 mx-auto mb-6 bg-gradient-to-br from-blue-100 to-purple-100 dark:from-blue-900/30 dark:to-purple-900/30 rounded-3xl flex items-center justify-center">
                            <Users className="w-10 h-10 text-slate-400 dark:text-slate-500" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-4 humanistic-serif">
                            Personalisierte Empfehlungen
                        </h3>
                        <p className="text-slate-600 dark:text-slate-400 mb-8 max-w-md mx-auto leading-relaxed">
                            Vervollständigen Sie Ihr Profil für maßgeschneiderte Förderempfehlungen
                        </p>
                        <Link to={createPageUrl("Lebenslagen")}>
                            <Button className="btn-ghost bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white border-none px-8 py-3 text-lg font-semibold rounded-2xl shadow-xl hover:shadow-2xl transform hover:scale-105 transition-all duration-300">
                                <Sparkles className="w-5 h-5 mr-2" />
                                Profil vervollständigen
                            </Button>
                        </Link>
                    </div>
                </CardContent>
            </Card>
        );
    }

    return (
        <Card className="border-none shadow-2xl h-full bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl glass-morphism">
            <CardHeader className="border-b border-white/10 p-8">
                <div className="flex items-center justify-between">
                    <CardTitle className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-3 humanistic-serif">
                        <div className="w-8 h-8 bg-gradient-to-br from-amber-400 to-orange-500 rounded-xl flex items-center justify-center shadow-lg">
                            <Star className="w-5 h-5 text-white" />
                        </div>
                        Für Sie empfohlen
                    </CardTitle>
                    <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white border-none px-4 py-2 rounded-xl font-semibold">
                        <Zap className="w-4 h-4 mr-2" />
                        KI-optimiert
                    </Badge>
                </div>
            </CardHeader>
            <CardContent className="p-0">
                <div className="space-y-0">
                    {aktuelleEmpfehlungen.map((leistung, index) => (
                        <div key={leistung.id} 
                             className="p-6 hover:bg-white/40 dark:hover:bg-slate-700/40 transition-all duration-300 border-b border-white/10 last:border-b-0 card-3d group">
                            <div className="space-y-4">
                                <div className="flex-1">
                                    <div className="flex items-center gap-3 mb-2">
                                        <h3 className="font-bold text-slate-800 dark:text-white text-lg humanistic-serif group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                                            {leistung.titel}
                                        </h3>
                                        {leistung.anspruchswahrscheinlichkeit && (
                                            <Badge className={
                                                leistung.anspruchswahrscheinlichkeit === 'Sehr hoch' 
                                                    ? 'bg-gradient-to-r from-green-400 to-emerald-500 text-white border-none'
                                                    : leistung.anspruchswahrscheinlichkeit === 'Hoch' 
                                                        ? 'bg-gradient-to-r from-blue-400 to-cyan-500 text-white border-none'
                                                        : 'bg-gradient-to-r from-amber-400 to-orange-500 text-white border-none'
                                            }>
                                                {leistung.anspruchswahrscheinlichkeit}
                                            </Badge>
                                        )}
                                        {index < 2 && (
                                            <Badge className="bg-gradient-to-r from-pink-400 to-rose-500 text-white border-none text-xs font-bold animate-pulse">
                                                ⭐ Top-Match
                                            </Badge>
                                        )}
                                    </div>
                                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-3">
                                        {leistung.kurzbeschreibung}
                                    </p>
                                    {leistung.empfehlungsgrund && (
                                        <div className="p-3 rounded-xl bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border-l-4 border-blue-400">
                                            <p className="text-sm text-blue-700 dark:text-blue-300 font-medium">
                                                💡 {leistung.empfehlungsgrund}
                                            </p>
                                        </div>
                                    )}
                                </div>
                                
                                <div className="flex items-center justify-between pt-2">
                                    <div className="flex flex-wrap items-center gap-2">
                                        <Badge className="bg-white/60 dark:bg-slate-700/60 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-600 backdrop-blur-sm">
                                            {leistung.kategorie}
                                        </Badge>
                                        {leistung.automatisierbar && (
                                            <Badge className="bg-gradient-to-r from-green-400 to-emerald-500 text-white border-none">
                                                <Check className="w-3 h-3 mr-1" />
                                                Auto-Check
                                            </Badge>
                                        )}
                                    </div>
                                    
                                    <Link 
                                        to={createPageUrl(`Pruefung?type=${leistung.typ}`)}
                                        onClick={() => handleRecommendationClick(leistung)}
                                    >
                                        <Button className="btn-ghost bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white border-none px-6 py-2 rounded-xl font-semibold shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-300">
                                            Prüfen
                                            <ArrowRight className="w-4 h-4 ml-2" />
                                        </Button>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </CardContent>
        </Card>
    );
}
